IsshMainBundle:
    resource: "@IsshMainBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern:   /login
    defaults:  { _controller: IsshMainBundle:Security:login }
register:
    pattern:   /register
    defaults:  { _controller: IsshMainBundle:Security:register }  
post:
    pattern:   /post
    defaults:  { _controller: IsshMainBundle:Home:post }      
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
home:
    pattern:   /
    defaults:  { _controller: IsshMainBundle:Home:index } 
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
