Issh\MainBundle\Entity\IsshSlaptastic:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    userId:
      type: integer
    postId:
      type: integer
    commentId:
      type: integer
    created:
      type: datetime
  lifecycleCallbacks: {  }
