Issh\MainBundle\Entity\IsshComment:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    postId:
      type: integer
    text:
      type: text
    created:
      type: datetime
    userId:
      type: integer      
  lifecycleCallbacks: {  }
