Issh\MainBundle\Entity\IsshPost:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    categoryId:
      type: integer      
    text:
      type: text
    userId:
      type: integer
    created:
      type: datetime
    updated:
      type: datetime      
  lifecycleCallbacks: 
    preUpdate: [setUpdated]
