<?php

namespace Issh\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IsshPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsshCommentRepository extends EntityRepository
{
    public function getLatestComments($limit = 5, $postID)
    {
        $dql = 'SELECT c FROM IsshMainBundle:IsshComment c WHERE c.IsshPost = :id '.
               'ORDER BY c.created DESC';
 
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('id', $postID);
        $query->setMaxResults($limit);
 
        return $query->getResult();
    }
}