<?php

namespace Issh\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IsshPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsshPostRepository extends EntityRepository
{
    public function getLatestPosts($limit = 5)
    {
        $dql = 'SELECT p, u, c FROM IsshMainBundle:IsshPost p LEFT JOIN p.IsshUser u LEFT JOIN p.IsshCategory c '.
               'ORDER BY p.created DESC';
 
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setMaxResults($limit);
 
        return $query->getResult();
    }
}