<?php

namespace Issh\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IsshPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsshSlaptasticRepository extends EntityRepository
{
    public function getNumSlaptastics($postID)
    {
        $dql = 'SELECT count(c) FROM IsshMainBundle:IsshSlaptastic c WHERE c.IsshPost = :id ';
 
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('id', $postID);
 
        return $query->getResult();
    }
}