<?php

namespace Issh\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    
    public function getLatestPosts($limit = 5)
    {
//        $dql = 'SELECT p, u, c, t FROM IsshMainBundle:IsshPost p, IsshMainBundle:IsshUser u, IsshMainBundle:IsshComment c ' .
//               'WHERE p.userId = u.id AND ' .
//               'INNER JOIN p.user u INNER JOIN p.category c INNER JOIN ' .
//               'p.tags t ORDER BY p.createdAt DESC';
// 
//        $query = $this->getEntityManager()->createQuery($dql);
//        $query->setMaxResults($limit);
// 
//        return $query->getResult();
    }
    
}